name: learn-to-code
channels:
  - conda-forge
dependencies:
  - python==3.9
  - flake8
  - black
  - mypy
  - pytest
  - pytest-cov
  - pytest-flake8
  - pytest-mypy
  - pytest-mock
  - isort
  - pre-commit
